### ISSUE TITLE
一个导出时候路径bug

### ISSUE THREAD

**Issue by sloth4413** [Roytin/Woo#1]
![sm 1nat 26rw5 b 08ogx](https://cloud.githubusercontent.com/assets/2508681/8222725/a463f82a-15a1-11e5-9823-d4f28e8e714b.jpg)

如图,我写好md后export就会出现问题。

**Comment by notlazychen** [comment]
这里的link指的是localhost下的路径，静态页面最后的路由差不多也是http://xxx/<link>是这一部分，所以这link是会被用来创建目录的，如果你填写百度的地址的话，无疑会发生文件夹名称错误。
